version: 2.1

orbs:
  win: circleci/windows@1.0.0

workflows:
  workflow:
    jobs:
      - go-test:
          name: Go 1.14
          docker-image: circleci/golang:1.14
      - go-test:
          name: Go 1.13
          docker-image: circleci/golang:1.13
      - go-test:
          name: Go 1.12
          docker-image: circleci/golang:1.12
          with-modules: false
          work-dir: /go/src/github.com/launchdarkly/go-test-helpers
      - go-test:
          name: Go 1.11
          docker-image: circleci/golang:1.11
          with-modules: false
          work-dir: /go/src/github.com/launchdarkly/go-test-helpers
      - go-test:
          name: Go 1.10
          docker-image: circleci/golang:1.10
          run-lint: false # the version of golangci-lint we're using doesn't work with older Go versions
          with-modules: false
          work-dir: /go/src/github.com/launchdarkly/go-test-helpers
      - go-test:
          name: Go 1.9
          docker-image: circleci/golang:1.9
          run-lint: false # the version of golangci-lint we're using doesn't work with older Go versions
          with-modules: false
          work-dir: /go/src/github.com/launchdarkly/go-test-helpers
      - go-test:
          name: Go 1.8
          docker-image: circleci/golang:1.8
          run-lint: false # the version of golangci-lint we're using doesn't work with older Go versions
          with-modules: false
          work-dir: /go/src/github.com/launchdarkly/go-test-helpers
      - go-test-windows:
          name: Windows

jobs:
  go-test:
    parameters:
      docker-image:
        type: string
      run-lint:
        type: boolean
        default: true
      with-modules:
        type: boolean
        default: true
      work-dir:
        type: string
        default: ~/project

    docker:
      - image: <<parameters.docker-image>>
        environment:
          CIRCLE_TEST_REPORTS: /tmp/circle-reports
          CIRCLE_ARTIFACTS: /tmp/circle-artifacts

    working_directory: <<parameters.work-dir>>

    steps:
      - checkout
      - run:
          name: install go-junit-report
          command: go get -u github.com/jstemmer/go-junit-report

      - unless:
          condition: <<parameters.with-modules>>
          steps:
            - run:
                name: get dependencies
                command: go get -t ./...

      - when:
          condition: <<parameters.run-lint>>
          steps:
            - run: make lint
      
      - run:
          name: Run tests
          command: |
            mkdir -p $CIRCLE_TEST_REPORTS
            mkdir -p $CIRCLE_ARTIFACTS
            trap "go-junit-report < $CIRCLE_ARTIFACTS/report.txt > $CIRCLE_TEST_REPORTS/junit.xml" EXIT
            make test | tee $CIRCLE_ARTIFACTS/report.txt

      - store_test_results:
          path: /tmp/circle-reports

      - store_artifacts:
          path: /tmp/circle-artifacts

  go-test-windows:
    executor:
      name: win/vs2019
      shell: powershell.exe

    environment:
      GOPATH: C:\Users\VssAdministrator\go

    steps:
      - checkout
      - run: go version
      - run:
          name: build and test
          command: |
            go test -race ./...
